Add reflection and refraction in RaytraceBenchmark
apt-sim/AdePT pull request #105
Opened 2021-03-31 17:57 UTC by antoniopetre

Add reflection and refraction model for transparent objects. Add exponential attenuation for rays which traverse transparent layers. Structure storing optical properties (transparency, refraction index, object color) for every logical volume.

2021-04-07 14:31 UTC, agheata requested changes
Looks good, it needs some modifications here and there plus some more detailed README.

2021-04-07 14:31 UTC, agheata commented on examples/Raytracer_Benchmark/RaytraceBenchmark.cu
> +__global__ void getAllLogicalVolumes(vecgeom::VPlacedVolume *currentVolume, vecgeom::Vector<vecgeom::LogicalVolume *> *container)
This looks quite inefficient as a way to extract the logical volumes in a vector. You don't need a (recursive) kernel doing it, you can try to use: CudaManager::LookupLogical(LogicalVolume const *const host_ptr) that returns the device pointer for each logical volume on the host. So if you need device pointers you can have just a loop on host on the vector of logical volumes stored by GeoManager (```GeoManager::GetAllLogicalVolumes()```) and get the device pointer using CudaManager.

2021-04-07 14:31 UTC, agheata commented on examples/Raytracer_Benchmark/RaytraceBenchmark.cu
> +  for (int i = 0; i < no_generations; ++i) {
You should probably have: `*value = false;` to start with, not having to care if the user of the function initialized it or not.

2021-04-07 14:31 UTC, agheata commented on examples/Raytracer_Benchmark/RaytraceBenchmark.cu
> +      *value = 1;
```suggestion
      *value = true;
```

2021-04-07 14:31 UTC, agheata commented on examples/Raytracer_Benchmark/RaytraceBenchmark.hpp
> +    while (check_used<backend>(rtdata, no_generations)) {
This loop would need to be explained in the README

2021-04-07 14:31 UTC, agheata commented on examples/Raytracer_Benchmark/Raytracer.cpp
> +                                 (medium_prop_next->refr_index * medium_prop_last->refr_index) > 1.;
Maybe the condition should be more strict here, you don't want to do refraction between 2 media having the same index, even if it is >1

2021-04-07 21:00 UTC, agheata commented on examples/Raytracer_Benchmark/CMakeLists.txt
> +target_compile_options(raytracercu PRIVATE "$<$<COMPILE_LANGUAGE:CUDA>:--extended-lambda;-fmad=false>")
Is it still the case after fixing the color addition order? Do you get different pictures if you disable this flag?

2021-04-08 11:16 UTC, antoniopetre commented on examples/Raytracer_Benchmark/CMakeLists.txt
> +target_compile_options(raytracercu PRIVATE "$<$<COMPILE_LANGUAGE:CUDA>:--extended-lambda;-fmad=false>")
Yes, I tried it and the pictures are different without this flag.

2021-04-09 08:25 UTC, agheata commented on examples/Raytracer_Benchmark/CMakeLists.txt
> +target_compile_options(raytracercu PRIVATE "$<$<COMPILE_LANGUAGE:CUDA>:--extended-lambda;-fmad=false>")
OK, to be put on the todo list for understanding why, but IMO should not block the PR

2021-04-09 19:36 UTC, agheata approved these changes

2021-04-09 19:37 UTC, merged