WIP: Move the asynchronous mode components into AdePT
apt-sim/AdePT pull request #325
Opened 2024-12-09 18:17 UTC by JuanGonzalezCaminero

Work in progress, the goal of this PR is to move the components found in the new asynchronous example into AdePT.

The "AdePTIntegration.*" files from the example actually correspond to the "AdePTTransport" components from the current synchronous mode.
Some components are incompatible with the current AdePT, but the main issue is that the example relies on compiling the CUDA files separately and linking them. AdePT is a header-only library so this can't be done, many of the changes focus on this

2025-01-27 14:57 UTC, SeverinDiederichs requested changes
Thanks for this huge efforts! There are a couple of things that need to be addressed i.e., removing the testField or removing a line that fixed a critical bug. Could you have a look please?

2025-01-27 14:57 UTC, SeverinDiederichs commented on include/AdePT/core/CommonStruct.h
> +  unique_ptr_cuda<TrackDataWithIDs, CudaHostDeleter<TrackDataWithIDs>> toDevice_host;                              ///< Tracks to be transported to the device
Could you make sure this is clang-formatted? This line is not formatted

2025-01-27 14:57 UTC, SeverinDiederichs commented on include/AdePT/core/AsyncAdePTTransport.hh
> +  std::vector<AdePTScoring*> fScoring;               ///< User scoring objects per G4 worker
This shows why we should refactor the header only approach.. Can we add a FIXME in the comment here, so we can easily find it again? I am not sure the pointer is deleted in the destructor

2025-01-27 14:57 UTC, SeverinDiederichs commented on include/AdePT/core/HostScoringImpl.cuh
> -  ResetBufferStatsGPU<<<1, 1, 0, stream>>>(hostScoring_dev);
Is this some accident in picking the wrong line in the re-basing?

This line fixed a very hard to trace bug that happened in very large events, see [this PR](https://github.com/apt-sim/AdePT/pull/329)

2025-01-27 14:57 UTC, SeverinDiederichs commented on include/AdePT/core/PerEventScoringImpl.cuh
> +// };
Could you add a comment on this? What is the state, why is it commented out but kept?

2025-01-27 14:57 UTC, SeverinDiederichs commented on include/AdePT/core/PerEventScoringImpl.cuh
> +// }
Could you please add a comment on the state of this part?

2025-01-27 14:57 UTC, SeverinDiederichs commented on include/AdePT/integration/AdePTTrackingManager.hh
> +  #endif
I guess this part is irrelevant for performance. Wouldn't it be easier to just use `std::shared_ptr` in both cases to simplify the code and make it more readable?

2025-01-27 14:57 UTC, SeverinDiederichs commented on include/AdePT/kernels/electrons.cuh
> +
```suggestion
#pragma message( "Compiling synchronous kernels")
```

Is the idea to have some compiler output in case one doesn't look at the cmake? Then I would probably make the output a bit clearer

2025-01-27 14:57 UTC, SeverinDiederichs commented on include/AdePT/magneticfield/fieldPropagatorConstBz.h
> +
```suggestion
```

Just some cleaning

2025-01-27 14:57 UTC, SeverinDiederichs commented on include/AdePT/navigation/AdePTNavigator.h
> +// #include <AdePT/navigation/LoopNavigator.h>
```suggestion
```

Just some cleaning

2025-01-27 14:57 UTC, SeverinDiederichs commented on test/CMakeLists.txt
> +# add_subdirectory(testField)
Does this not compile or work anymore? Or can this be activated again? What is the status of this?

2025-01-27 14:57 UTC, SeverinDiederichs commented on src/AdePTTrackingManager.cc
> +
This looks very similar to the AdePTTransportFactory that we had before, just that the transport factory didn't require the #ifdefs. Just for the future, but I think that should be cleaned.

2025-01-27 14:57 UTC, SeverinDiederichs commented on src/AdePTTrackingManager.cu
> +// #include <cub/device/device_merge_sort.cuh>
```suggestion
```
Just some cleaning

2025-01-27 15:35 UTC, JuanGonzalezCaminero commented on src/AdePTTrackingManager.cc
> +
The #ifdefs are required since this part of the code is common to both backends. When using the sync mode `AsyncAdePTTransport` is not defined.
About the name, I'm not sure if it's correct to refer to a free function as a factory, and the purpose of it is more to make it work like a singleton. We should review whether this is the best way to instantiate the async backend

2025-01-27 15:48 UTC, JuanGonzalezCaminero commented on include/AdePT/core/HostScoringImpl.cuh
> -  ResetBufferStatsGPU<<<1, 1, 0, stream>>>(hostScoring_dev);
Probably a rebase accident, yes, I'll add the line back

2025-01-27 20:11 UTC, JuanGonzalezCaminero commented on include/AdePT/core/AsyncAdePTTransport.hh
> +  std::vector<AdePTScoring*> fScoring;               ///< User scoring objects per G4 worker
Now using a `unique_ptr` again, the scoring objects are no longer stored as pointers either. This was a leftover from the first stages of the migration, thanks for pointing out

2025-01-27 20:14 UTC, JuanGonzalezCaminero commented on include/AdePT/integration/AdePTTrackingManager.hh
> +  #endif
I don't see an advantage to using a more complex solution where `unique_ptr` is enough. Could also be more error-prone

2025-01-27 20:15 UTC, JuanGonzalezCaminero commented on include/AdePT/kernels/electrons.cuh
> +
Was for debug, removed.

2025-01-28 08:11 UTC, SeverinDiederichs commented on src/AdePTTrackingManager.cc
> +
Sorry, my point was not phrased well:
I think the #ifdefs in the AdePTTrackingManager could be hidden inside an InstantiateAdePT function, i.e., it gets called for both and then internally does something different according to the ifdefs.

2025-01-28 11:21 UTC, SeverinDiederichs approved these changes
No more comments from my side, thanks for these efforts!

2025-01-28 11:59 UTC, agheata commented on src/AdePTTrackingManager.cc
> +
Let's say this can be done as a cleanup later, for now the priority is to have it merged

2025-01-28 12:15 UTC, merged